<a href="https://colab.research.google.com/github/pingstech/ZeroToHero-ML/blob/main/03_NumpyDenemeler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
array=np.array([1,2,3,5]) #1x4 lük vektör oluşturduk
array

array([1, 2, 3, 5])

In [ ]:
print(array.shape)

(4,)


In [ ]:
temp_array=array.reshape(2,2)
temp_array

array([[1, 2],
       [3, 5]])

In [ ]:
print("Yeni array satır sütüun sayısı : ",temp_array.shape)
print("Yeni array boyutu:",temp_array.ndim)

Yeni array satır sütüun sayısı :  (2, 2)
Yeni array boyutu: 2


In [ ]:
print("Veri tipi",temp_array.dtype.name)  

Veri tipi int64


In [ ]:
print("Ölçüsü:",temp_array.size)

Ölçüsü: 4


In [ ]:
print("tipi:",type(temp_array))

tipi: <class 'numpy.ndarray'>


In [ ]:
array2=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
zeros=np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
zeros[0,0]=5
print("Yeni matrix:",zeros)

Yeni matrix: [[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
ones=np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
empty_array=np.empty((3,4))
empty_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
temp_array2=np.arange(10,50,5)
temp_array2

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
temp_array3=np.linspace(10,50,20) # 10 dan 50 ye kadar 50 dahil sayı yazar
temp_array3

array([10.        , 12.10526316, 14.21052632, 16.31578947, 18.42105263,
       20.52631579, 22.63157895, 24.73684211, 26.84210526, 28.94736842,
       31.05263158, 33.15789474, 35.26315789, 37.36842105, 39.47368421,
       41.57894737, 43.68421053, 45.78947368, 47.89473684, 50.        ])

In [ ]:
#------------------ NUMPY BASİC OPERATİONS  ------------------

In [ ]:
temp_array=np.array([1,2,3])
temp_array2=np.array([4,5,6])

print("Sum of Array:",temp_array+temp_array2)
print("Subtract of Array:",temp_array-temp_array2)
print("Multiple of Array:",temp_array*temp_array2)
print("Power of Array:",temp_array**temp_array2)

Sum of Array: [5 7 9]
Subtract of Array: [-3 -3 -3]
Multiple of Array: [ 4 10 18]
Power of Array: [  1  32 729]


In [ ]:
print(np.sin(temp_array))

[0.84147098 0.90929743 0.14112001]


In [ ]:
print(temp_array<2)

[ True False False]


In [ ]:
temp_array.dot(temp_array2)

32

In [ ]:
temp_array=np.array([[1,2,3],[4,5,6]])
temp_array2=np.array([[1,2,3],[4,5,6]])

In [ ]:
temp_array.dot(temp_array2) # satır sütün uyumsuzluğu olduğu için olmadı "temp_array2" nin transpozunu alarak bu durumu düzelticez

ValueError: ignored

In [ ]:
temp_array.dot(temp_array2.T)

array([[14, 32],
       [32, 77]])

In [ ]:
temp_array=np.random.random((5,5))
temp_array

array([[0.16071816, 0.24786759, 0.28724614, 0.57751277, 0.90943629],
       [0.49197301, 0.1410036 , 0.04714147, 0.50700771, 0.76367076],
       [0.70630163, 0.57534854, 0.94257332, 0.31890928, 0.69545053],
       [0.41902537, 0.6265754 , 0.59131906, 0.43656426, 0.5703372 ],
       [0.47524122, 0.01110084, 0.53248887, 0.09477561, 0.00776377]])

In [ ]:
temp_array.sum()

11.137352412969639

In [ ]:
print("Min value of array: ",temp_array.min())
print("Max value of array: ",temp_array.max())
print("Sum of array: ",temp_array.sum())

Min value of array:  0.00776377430778441
Max value of array:  0.942573320774761
Sum of array:  11.137352412969639


In [ ]:
print(temp_array.sum(axis=0)) # sütün toplaması yapar

[2.25325939 1.60189598 2.40076886 1.93476963 2.94665855]


In [ ]:
print(temp_array.sum(axis=1)) # satır toplaması yapar

[2.18278095 1.95079655 3.2385833  2.64382129 1.12137032]


In [ ]:
print("Karekökü: ",(np.sqrt(temp_array)))
print("Karesi",np.square(temp_array))

Karekökü:  [[0.4008967  0.49786302 0.53595348 0.75994261 0.95364369]
 [0.70140788 0.37550446 0.21712086 0.71204474 0.87388258]
 [0.84041753 0.75851733 0.97086215 0.56472053 0.83393677]
 [0.64732169 0.79156516 0.76897273 0.6607301  0.75520672]
 [0.68937742 0.10536054 0.72971835 0.30785647 0.08811228]]
Karesi [[2.58303282e-02 6.14383426e-02 8.25103437e-02 3.33520996e-01
  8.27074364e-01]
 [2.42037440e-01 1.98820161e-02 2.22231799e-03 2.57056816e-01
  5.83193036e-01]
 [4.98861994e-01 3.31025941e-01 8.88444465e-01 1.01703128e-01
  4.83651441e-01]
 [1.75582261e-01 3.92596734e-01 3.49658228e-01 1.90588357e-01
  3.25284517e-01]
 [2.25854219e-01 1.23228721e-04 2.83544402e-01 8.98241604e-03
  6.02761915e-05]]


In [ ]:
print(np.add(temp_array,temp_array))

[[0.32143633 0.49573518 0.57449228 1.15502553 1.81887258]
 [0.98394601 0.28200721 0.09428294 1.01401542 1.52734153]
 [1.41260326 1.15069708 1.88514664 0.63781856 1.39090106]
 [0.83805074 1.2531508  1.18263812 0.87312853 1.14067439]
 [0.95048244 0.02220169 1.06497775 0.18955122 0.01552755]]


In [ ]:
# --------------------------------- INDEXING AND SLICING ---------------------------------

In [ ]:
import numpy as np
temp_array=np.array([1,2,3,4,5,6,7])
print(temp_array[0:4]) # 0'dan 4'e kadar 4 dahil değil

[1 2 3 4]


In [ ]:
reverse_array=temp_array[::-1] #Ters çevirdik
reverse_array

array([7, 6, 5, 4, 3, 2, 1])

In [ ]:
temp_array2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
temp_array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
print(temp_array2[0,0])
print(temp_array2[0,1])
print(temp_array2[1,0])
print(temp_array2[1,1])

1
2
6
7


In [ ]:
print(temp_array2[:,1])
print(temp_array2[:,0])
print(temp_array2[0,:])
print(temp_array2[1,:])

[2 7]
[1 6]
[1 2 3 4 5]
[ 6  7  8  9 10]


In [ ]:
print(temp_array2[-1,:])  # Son satır
print(temp_array2[:,-1])  # Son sütün

[ 6  7  8  9 10]
[ 5 10]


In [ ]:
# --------------------------------- SHAPE MANIPULATION ---------------------------------

In [ ]:
temp_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
temp_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# "temp_array"i TEK SATIR HALİNDE YANİ VEKTÖR HALDE YAZACAĞIZ
temp_vector=temp_array.ravel()
temp_vector

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# "temp_vector" VEKTÖRÜNÜ ESKİ HALİNE YANİ MATRİS HALİNE GETİRECEĞİZ
temp_array2=temp_vector.reshape(3,3)
temp_array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# ŞİMDİ TRANSPOZUNU ALACAĞIZ
temp_transpose=temp_array.T
temp_transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
print(temp_transpose.shape)

(3, 3)


In [ ]:
#resize ın reshape'den farkı

In [ ]:
temp_array=np.array([[1,2],[3,4],[4,6]])
temp_array

array([[1, 2],
       [3, 4],
       [4, 6]])

In [ ]:
print("Reshape\n",temp_array.reshape(2,3))
print("----------------------------------")
print("Reshape Sonrası Orjinal Matris\n",temp_array)
print("----------------------------------")
print("Resize\n",temp_array.resize((2,3))) # Bir sonuç vermez çünkü direkt "temp_array"in içine yazıyor
print("----------------------------------")
print("Resize Sonrası Orjinal Matris\n",temp_array)

Reshape
 [[1 2 3]
 [4 4 6]]
----------------------------------
Reshape Sonrası Orjinal Matris
 [[1 2]
 [3 4]
 [4 6]]
----------------------------------
Resize
 None
----------------------------------
Resize Sonrası Orjinal Matris
 [[1 2 3]
 [4 4 6]]


In [ ]:
# --------------------------------- STACKING ARRAYS ---------------------------------

In [ ]:
temp_array=np.array([[1,2],[3,4]])
temp_array2=np.array([[-1,-2],[-3,-4]])
print("Temp Array\n",temp_array)
print("----------------------------------")
print("Temp Array 2\n",temp_array2)
print("----------------------------------")

Temp Array
 [[1 2]
 [3 4]]
----------------------------------
Temp Array 2
 [[-1 -2]
 [-3 -4]]
----------------------------------


In [ ]:
# DİKEY BİRLEŞTİRME
temp_vStack=np.vstack((temp_array,temp_array2))
print("Dikey Birleştirme Sonucu\n",temp_vStack)

Dikey Birleştirme Sonucu
 [[ 1  2]
 [ 3  4]
 [-1 -2]
 [-3 -4]]


In [ ]:
# YATAY BİRLEŞTİRME
temp_hStack=np.hstack((temp_array,temp_array2))
print("Yatay Birleştirme Sonucu\n",temp_hStack)

Yatay Birleştirme Sonucu
 [[ 1  2 -1 -2]
 [ 3  4 -3 -4]]


In [ ]:
# --------------------------------- CONVERTING AND COPY ARRAY ---------------------------------

In [ ]:
temp_list=[1,2,3,4]
temp_array=np.array(temp_list)
temp_array

array([1, 2, 3, 4])

In [ ]:
temp_list2=list(temp_array)
temp_list2

[1, 2, 3, 4]

In [ ]:
temp_array2=np.array([1,2,3])
temp_array3=temp_array2
temp_array4=temp_array2

In [ ]:
# Yukarıda yaptığımız işlem ile hafızada(memoryde) aynı alanı ayırdığımız için aşağıdaki sonuçlara erişiyoruz
temp_array3[0]=5
print("Temp Array2\n",temp_array2)
print("----------------------------------")
print("Temp Array3\n",temp_array3)
print("----------------------------------")
print("Temp Array4\n",temp_array4)
print("----------------------------------")

Temp Array2
 [5 2 3]
----------------------------------
Temp Array3
 [5 2 3]
----------------------------------
Temp Array4
 [5 2 3]
----------------------------------


In [ ]:
# Yukarıdaki olayların olmasını istemiyorsak
temp_array5=np.array([1,2,3])
temp_array6=temp_array5.copy()
temp_array7=temp_array5.copy()
temp_array6[0]=5
print("Temp Array5\n",temp_array5)
print("----------------------------------")
print("Temp Array6\n",temp_array6)
print("----------------------------------")
print("Temp Array7\n",temp_array7)
print("----------------------------------")

Temp Array5
 [1 2 3]
----------------------------------
Temp Array6
 [5 2 3]
----------------------------------
Temp Array7
 [1 2 3]
----------------------------------


NameError: ignored